---
title: "Exploratory Data Analysis"
output: html_notebook
---
<br/>

## I. Vegas Hotel Dataset: 
<br/>
**1. Reading Vegas hotel data from csv file and viewing the structure of the dataset:**
```{R}
vegashotels = read.csv2("vegashotels-1.csv", stringsAsFactors = TRUE)
str(vegashotels)
```
From the structure of the dataset below are the categorical and numerical attributes:

* Categorical features: 
  + User.country, Score, Period.of.stay, Traveler.type, Pool, Gym, Tennis.court, Spa, Casino, Free.internet, Hotel.name, Hotel.stars, User.continent, Review.month, and Review.weekday (total of 15 categorical attributes)  
<br/>
* Numerical features:
  + Nr..reviews, Nr..hotel.reviews, Helpful.votes, Nr..rooms,and Member.years (total of 5 numerical attributes)

<br/>  
**2. 
<br/>
    i. Summary statistics of the dataset:**
```{R}
  vegashotels_summary <- summary(vegashotels)
  vegashotels_summary
```
<br/>
    **ii. Missing values in the variables:**
```{R}
colSums(is.na(vegashotels))
```
* There are no missing values in the dataset

<br/>
**3. Histogram of score variable:**
```{R, echo = F}
attach(vegashotels)
```
```{R}
hist(Score, main = "Histogram of Vegas hotels score", xlab = "Score", col = "#DEBAC0", labels = TRUE, breaks = c(0,1,2,3,4,5), ylim = c(0,300))
```
* From the histogram we can say that 227 of the 504 vegas hotels have a score of 5 which is about 45% of them. And a total of 391 hotels out of 504 hotels have a score of either 4 or 5 which is around 77.5% of the vegas hotels.

<br/>
**4. Mode of score variable:**
```{R}
score_table = table(Score)
score_mode = as.numeric(names(score_table))[score_table == max(score_table)]
score_mode
```
* Mode of the Score variable is 5 meaning a score of 5 is more common than other scores for Vegas hotels.

<br/>
**5. Quantile and median for Score:**
```{R}
quantile(Score)
```
* Median of the Score variable using quantile function is 4

```{R}
median(Score)
```
<br/>
**6. sentiment factor variable that takes the value “positive” if score is 4 or 5 and “negative” otherwise:**
```{R}
sentiment = factor(ifelse(Score==4 | Score == 5,"positive","negative"))
sentiment
```
<br/>
**7. Frequency of sentiment and Score variables**
```{R}
summary(sentiment)

negative_freq = table(Score)[[1]] + table(Score)[[2]] + table(Score)[[3]]
negative_freq

positive_freq = table(Score)[[4]] + table(Score)[[5]]
positive_freq
```
* Frequency for the “positive” sentiment is equal to the combined frequency of 4 and 5 for the Score and frequency for the “negative” sentiment is equal to the combined frequency of the rest of the values the Score.
































